// 手順の一覧。番号・名前・グループは SpeedCubeDB に合わせている。
// 手順は各ケースの上位 3 つから、持ち替え(x / y / z)の無いものを選んだ。無いケースは 1 位のもの。
// 正しさは algs.test.ts がシミュレータで確かめている。

export type AlgSetName = 'F2L' | 'OLL' | 'PLL';
export type AlgCase = { name: string; group: string; alg: string };
export type AlgSet = { groups: Array<{ key: string; title: string }>; cases: AlgCase[] };

export const ALG_SETS: Record<AlgSetName, AlgSet> = {
  // 右手前のスロットに入れる。白を下、緑を手前
  F2L: {
    groups: [
      { key: 'Free Pairs', title: '基本形' },
      { key: 'Disconnected Pairs', title: '離れたペア' },
      { key: 'Connected Pairs', title: 'くっついたペア' },
      { key: 'Corner In Slot', title: '角がスロットにある' },
      { key: 'Edge In Slot', title: '辺がスロットにある' },
      { key: 'Pieces In Slot', title: '両方スロットにある' },
    ],
    cases: [
      { name: '1', group: 'Free Pairs', alg: "U R U' R'" },
      { name: '2', group: 'Free Pairs', alg: "F R' F' R" },
      { name: '3', group: 'Free Pairs', alg: "F' U' F" },
      { name: '4', group: 'Free Pairs', alg: "R U R'" },
      { name: '5', group: 'Disconnected Pairs', alg: "U' R U R' U2 R U' R'" },
      { name: '6', group: 'Disconnected Pairs', alg: "U' r U' R' U R U r'" },
      { name: '7', group: 'Disconnected Pairs', alg: "U' R U2 R' U' R U2 R'" },
      { name: '8', group: 'Disconnected Pairs', alg: "r' U2 R2 U R2 U r" },
      { name: '9', group: 'Disconnected Pairs', alg: "U' R U' R' U F' U' F" },
      { name: '10', group: 'Disconnected Pairs', alg: "U' R U R' U R U R'" },
      { name: '11', group: 'Connected Pairs', alg: "U' R U2 R' U F' U' F" },
      { name: '12', group: 'Connected Pairs', alg: "R U' R' U R U' R' U2 R U' R'" },
      { name: '13', group: 'Connected Pairs', alg: "R U' R' U R' F R F' R U' R'" },
      { name: '14', group: 'Connected Pairs', alg: "U' R U' R' U R U R'" },
      { name: '15', group: 'Connected Pairs', alg: "R U R' U2 R U' R' U R U' R'" },
      { name: '16', group: 'Connected Pairs', alg: "R U' R' U2 F' U' F" },
      { name: '17', group: 'Connected Pairs', alg: "R U2 R' U' R U R'" },
      { name: '18', group: 'Connected Pairs', alg: "F' U2 F U F' U' F" },
      { name: '19', group: 'Disconnected Pairs', alg: "U R U2 R' U R U' R'" },
      { name: '20', group: 'Disconnected Pairs', alg: "U' R U' R2 F R F' R U' R'" },
      { name: '21', group: 'Disconnected Pairs', alg: "U2 R U R' U R U' R'" },
      { name: '22', group: 'Disconnected Pairs', alg: "F' L' U2 L F" },
      { name: '23', group: 'Connected Pairs', alg: "U R U' R' U' R U' R' U R U' R'" },
      { name: '24', group: 'Connected Pairs', alg: "F U R U' R' F' R U' R'" },
      { name: '25', group: 'Corner In Slot', alg: "U' R' F R F' R U R'" },
      { name: '26', group: 'Corner In Slot', alg: "U R U' R' F R' F' R" },
      { name: '27', group: 'Corner In Slot', alg: "R U' R' U R U' R'" },
      { name: '28', group: 'Corner In Slot', alg: "R U R' U' F R' F' R" },
      { name: '29', group: 'Corner In Slot', alg: "R' F R F' U R U' R'" },
      { name: '30', group: 'Corner In Slot', alg: "R U R' U' R U R'" },
      { name: '31', group: 'Edge In Slot', alg: "U' R' F R F' R U' R'" },
      { name: '32', group: 'Edge In Slot', alg: "U R U' R' U R U' R' U R U' R'" },
      { name: '33', group: 'Edge In Slot', alg: "U' R U' R' U2 R U' R'" },
      { name: '34', group: 'Edge In Slot', alg: "U R U R' U2 R U R'" },
      { name: '35', group: 'Edge In Slot', alg: "U' R U R' U F' U' F" },
      { name: '36', group: 'Edge In Slot', alg: "U F' U' F U' R U R'" },
      { name: '37', group: 'Pieces In Slot', alg: "R2 U2 F R2 F' U2 R' U R'" },
      { name: '38', group: 'Pieces In Slot', alg: "R U' R' U' R U R' U2 R U' R'" },
      { name: '39', group: 'Pieces In Slot', alg: "R U' R' U R U2 R' U R U' R'" },
      { name: '40', group: 'Pieces In Slot', alg: "F' L' U2 L F R U R'" },
      { name: '41', group: 'Pieces In Slot', alg: "R U' R' F' L' U2 L F" },
    ],
  },
  OLL: {
    groups: [
      { key: 'OCLL', title: '十字(角だけ)' },
      { key: 'Dot Case', title: 'ドット' },
      { key: 'Line Shapes', title: '線' },
      { key: 'L Shapes', title: 'L 形' },
      { key: 'P Shapes', title: 'P 形' },
      { key: 'T Shapes', title: 'T 形' },
      { key: 'C Shapes', title: 'C 形' },
      { key: 'W Shapes', title: 'W 形' },
      { key: 'Square Shapes', title: '四角' },
      { key: 'Lightning Shapes', title: '稲妻' },
      { key: 'Fish Shapes', title: '魚' },
      { key: 'Knight Move Shapes', title: '桂馬' },
      { key: 'Awkward Shapes', title: 'いびつ' },
      { key: 'All Corners Oriented', title: '角が揃っている' },
    ],
    cases: [
      { name: '1', group: 'Dot Case', alg: "R U2 R2 F R F' U2 R' F R F'" },
      { name: '2', group: 'Dot Case', alg: "F R U R' U' S R U R' U' f'" },
      { name: '3', group: 'Dot Case', alg: "r' R2 U R' U r U2 r' U M'" },
      { name: '4', group: 'Dot Case', alg: "R' F R F' U' S R' U' R U R S'" },
      { name: '5', group: 'Square Shapes', alg: "r' U2 R U R' U r" },
      { name: '6', group: 'Square Shapes', alg: "r U2 R' U' R U' r'" },
      { name: '7', group: 'Lightning Shapes', alg: "r U R' U R U2 r'" },
      { name: '8', group: 'Lightning Shapes', alg: "l' U' L U' L' U2 l" },
      { name: '9', group: 'Fish Shapes', alg: "R U2 R' U' S' R U' R' S" },
      { name: '10', group: 'Fish Shapes', alg: "R U R' U R' F R F' R U2 R'" },
      { name: '11', group: 'Lightning Shapes', alg: "r' R2 U R' U R U2 R' U M'" },
      { name: '12', group: 'Lightning Shapes', alg: "F R U R' U' F' U F R U R' U' F'" },
      { name: '13', group: 'Knight Move Shapes', alg: "F U R U2 R' U' R U R' F'" },
      { name: '14', group: 'Knight Move Shapes', alg: "R' F R U R' F' R F U' F'" },
      { name: '15', group: 'Knight Move Shapes', alg: "r' U' r R' U' R U r' U r" },
      { name: '16', group: 'Knight Move Shapes', alg: "r U r' R U R' U' r U' r'" },
      { name: '17', group: 'Dot Case', alg: "R U R' U R' F R F' U2 R' F R F'" },
      { name: '18', group: 'Dot Case', alg: "r U R' U R U2 r2 U' R U' R' U2 r" },
      { name: '19', group: 'Dot Case', alg: "M U R U R' U' M' R' F R F'" },
      { name: '20', group: 'Dot Case', alg: "r U R' U' M2 U R U' R' U' M'" },
      { name: '21', group: 'OCLL', alg: "R U R' U R U' R' U R U2 R'" },
      { name: '22', group: 'OCLL', alg: "R U2 R2 U' R2 U' R2 U2 R" },
      { name: '23', group: 'OCLL', alg: "R2 D R' U2 R D' R' U2 R'" },
      { name: '24', group: 'OCLL', alg: "r U R' U' r' F R F'" },
      { name: '25', group: 'OCLL', alg: "R U2 R D R' U2 R D' R2" },
      { name: '26', group: 'OCLL', alg: "R' U' R U' R' U2 R" },
      { name: '27', group: 'OCLL', alg: "R U R' U R U2 R'" },
      { name: '28', group: 'All Corners Oriented', alg: "r U R' U' M U R U' R'" },
      { name: '29', group: 'Awkward Shapes', alg: "r2 D' r U r' D r2 U' r' U' r" },
      { name: '30', group: 'Awkward Shapes', alg: "y2 F U R U2 R' U' R U2 R' U' F'" },
      { name: '31', group: 'P Shapes', alg: "R' U' F U R U' R' F' R" },
      { name: '32', group: 'P Shapes', alg: "S R U R' U' R' F R f'" },
      { name: '33', group: 'T Shapes', alg: "R U R' U' R' F R F'" },
      { name: '34', group: 'C Shapes', alg: "F R U R' U' R' F' r U R U' r'" },
      { name: '35', group: 'Fish Shapes', alg: "R U2 R2 F R F' R U2 R'" },
      { name: '36', group: 'W Shapes', alg: "y R U R2 F' U' F U R2 U2 R'" },
      { name: '37', group: 'Fish Shapes', alg: "F R' F' R U R U' R'" },
      { name: '38', group: 'W Shapes', alg: "R U R' U R U' R' U' R' F R F'" },
      { name: '39', group: 'Lightning Shapes', alg: "y' f' r U r' U' r' F r S" },
      { name: '40', group: 'Lightning Shapes', alg: "R r D r' U r D' r' U' R'" },
      { name: '41', group: 'Awkward Shapes', alg: "y2 R U R' U R U2 R' F R U R' U' F'" },
      { name: '42', group: 'Awkward Shapes', alg: "R' U' R U' R' U2 R F R U R' U' F'" },
      { name: '43', group: 'P Shapes', alg: "f' L' U' L U f" },
      { name: '44', group: 'P Shapes', alg: "f R U R' U' f'" },
      { name: '45', group: 'T Shapes', alg: "F R U R' U' F'" },
      { name: '46', group: 'C Shapes', alg: "R' U' R' F R F' U R" },
      { name: '47', group: 'L Shapes', alg: "F' L' U' L U L' U' L U F" },
      { name: '48', group: 'L Shapes', alg: "F R U R' U' R U R' U' F'" },
      { name: '49', group: 'L Shapes', alg: "l U' l2 U l2 U l2 U' l" },
      { name: '50', group: 'L Shapes', alg: "r' U r2 U' r2 U' r2 U r'" },
      { name: '51', group: 'Line Shapes', alg: "f R U R' U' R U R' U' f'" },
      { name: '52', group: 'Line Shapes', alg: "R U R' U R U' B U' B' R'" },
      { name: '53', group: 'L Shapes', alg: "r' U' R U' R' U R U' R' U2 r" },
      { name: '54', group: 'L Shapes', alg: "r U R' U R U' R' U R U2 r'" },
      { name: '55', group: 'Line Shapes', alg: "R U2 R2 U' R U' R' U2 F R F'" },
      { name: '56', group: 'Line Shapes', alg: "r U r' U R U' R' U R U' R' r U' r'" },
      { name: '57', group: 'All Corners Oriented', alg: "R U R' U' M' U R U' r'" },
    ],
  },
  PLL: {
    groups: [
      { key: 'EPLL', title: '辺だけ' },
      { key: 'Adj Swap', title: '隣の角を交換' },
      { key: 'Opp Swap', title: '対角の角を交換' },
    ],
    cases: [
      { name: 'Aa', group: 'Adj Swap', alg: "x R' U R' D2 R U' R' D2 R2 x'" },
      { name: 'Ab', group: 'Adj Swap', alg: "x R2 D2 R U R' D2 R U' R x'" },
      { name: 'E', group: 'Opp Swap', alg: "R2 U F' R' U R U' R' U R U' R' U R U' F U' R2" },
      { name: 'F', group: 'Adj Swap', alg: "R' U R U' R2 F' U' F U R F R' F' R2" },
      { name: 'Ga', group: 'Adj Swap', alg: "R2 U R' U R' U' R U' R2 D U' R' U R D'" },
      { name: 'Gb', group: 'Adj Swap', alg: "D R' U' R U D' R2 U R' U R U' R U' R2" },
      { name: 'Gc', group: 'Adj Swap', alg: "R2 U' R U' R U R' U R2 D' U R U' R' D" },
      { name: 'Gd', group: 'Adj Swap', alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'" },
      { name: 'H', group: 'EPLL', alg: 'M2 U M2 U2 M2 U M2' },
      { name: 'Ja', group: 'Adj Swap', alg: "L' U' L F L' U' L U L F' L2 U L" },
      { name: 'Jb', group: 'Adj Swap', alg: "R U R' F' R U R' U' R' F R2 U' R'" },
      { name: 'Na', group: 'Opp Swap', alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'" },
      { name: 'Nb', group: 'Opp Swap', alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R" },
      { name: 'Ra', group: 'Adj Swap', alg: "L U2 L' U2 L F' L' U' L U L F L2" },
      { name: 'Rb', group: 'Adj Swap', alg: "R' U2 R U2 R' F R U R' U' R' F' R2" },
      { name: 'T', group: 'Adj Swap', alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
      { name: 'Ua', group: 'EPLL', alg: "R U R' U R' U' R2 U' R' U R' U R" },
      { name: 'Ub', group: 'EPLL', alg: "R' U R' U' R' U' R' U R U R2" },
      { name: 'V', group: 'Opp Swap', alg: "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2" },
      { name: 'Y', group: 'Opp Swap', alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
      { name: 'Z', group: 'EPLL', alg: "M' U' M2 U' M2 U' M' U2 M2" },
    ],
  },
};
